---
version: "2.0"

services:
  mongo:
    image: mongo:latest
    params:
      storage:
        data:
          mount: /var/lib/mongodb
    expose:
      - port: 27017
        to:
          - global: true
    env:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
profiles:
  compute:
    mongo:
      resources:
        cpu:
          units: 0.2
        memory:
          size: 256Mi
        storage:
          - size: 1Gi
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta2
  placement:
    akash:
      pricing:
        mongo:
          denom: uakt
          amount: 1000.1
deployment:
  mongo:
    akash:
      profile: mongo
      count: 1
